/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        gray: {
          50: 'var(--color-gray-50)',
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-900)',
        },
        primary: {
          100: 'var(--color-primary-100)',
          150: 'var(--color-primary-150)',
          200: 'var(--color-primary-200)',
          250: 'var(--color-primary-250)',
          300: 'var(--color-primary-300)',
          350: 'var(--color-primary-350)',
          400: 'var(--color-primary-400)',
          450: 'var(--color-primary-450)',
          500: 'var(--color-primary-500)',
          550: 'var(--color-primary-550)',
          600: 'var(--color-primary-600)',
          650: 'var(--color-primary-650)',
          700: 'var(--color-primary-700)',
          DEFAULT: 'var(--color-primary-450)',
        },
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        serious: 'var(--color-serious)',
        danger: 'var(--color-danger)',
        info: 'var(--color-info)',
        bg: 'var(--color-bg)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          muted: 'var(--color-surface-muted)',
        },
        cta: {
          DEFAULT: 'var(--color-cta)',
          hover: 'var(--color-cta-hover)',
          active: 'var(--color-cta-active)',
        },
        border: 'var(--color-border)',
        text: {
          DEFAULT: 'var(--color-text)',
          muted: 'var(--color-text-muted)',
          subtle: 'var(--color-text-subtle)',
        },
      },
      fontFamily: {
        sans: ['var(--font-family-sans)'],
        // New design system's fonts (see tokens.css) — not yet applied anywhere.
        body: ['var(--font-family-body)'],
        mono: ['var(--font-family-mono)'],
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        // New design system's "glow" elevation scale (see tokens.css) — not yet applied anywhere.
        'glow-xs': 'var(--shadow-glow-xs)',
        'glow-sm': 'var(--shadow-glow-sm)',
        'glow-md': 'var(--shadow-glow-md)',
        'glow-lg': 'var(--shadow-glow-lg)',
      },
    },
  },
  plugins: [],
};
